spring.application.name = digileave
server.port = 8080
spring.data.mongodb.uri = mongodb://localhost:27017/DigiLeave

spring.security.oauth2.client.registration.google.client-id= ${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret = ${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email